# [toolchain]

# [features]
# resolution = true
# skip-lint = false

# [programs.localnet]
# programs_patreonix = "Dshr8XRjH6VjbuA7o4NjBDYzmc2XTKf74CKhWW9XCXiz"

# [registry]
# url = "https://api.apr.dev"

# [provider]
# cluster = "Localnet"
# wallet = "~/.config/solana/id.json"

# [scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[features]
seeds = false
skip-lint = false

[programs.localnet]
patreonix = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"