import {
  ArrowLeft,
  ArrowRight,
  Check,
  FileText,
  BarChart,
  Layers,
  Target,
  //@ts-ignore
  type Icon as LucideIcon,
  //@ts-ignore
  LucideIcon,
  Image,
  FileAudio,
  Video,
  Calendar,
  Heart,
  MessageCircle,
  MoreHorizontal,
  Save,
  Bookmark,
  Share,
  Edit,
  Plus,
  Eye,
  UserPlus,
  DollarSign,
  Upload,
} from "lucide-react";
import { CgSpinnerTwo } from "react-icons/cg";
import { IoRefresh } from "react-icons/io5";

export type Icon = typeof LucideIcon;

export const Icons = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  check: Check,
  fileText: FileText,
  barChart: BarChart,
  layers: Layers,
  target: Target,
  image: Image,
  video: Video,
  audio: FileAudio,
  calendar: Calendar,
  heart: Heart,
  messageCircle: MessageCircle,
  moreHorizontal: MoreHorizontal,
  save: Save,
  bookmark: Bookmark,
  share: Share,
  edit: Edit,
  plus: Plus,
  eye: Eye,
  userPlus: UserPlus,
  dollarSign: DollarSign,
  upload: Upload,
  spinner: CgSpinnerTwo,
  refresh: IoRefresh,
};
