[toolchain]

[features]
resolution = true
skip-lint = false


[programs.localnet]
patreonix_programms = "4iL34RsAAc1i4wYBCotcUoHdohPVZf5BBberACyxZ37Z"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"
# wallet = "/home/ramkumar/.config/solana/id.json"  


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"
